[ style ][ ui > login ,signup ]회원가입 및 로그인 퍼블리싱 작업
team-archivist/archivist_frontend pull request #6
Opened 2023-12-03 13:17 UTC by divinity6

회원가입 및 로그인 퍼블리싱 및 스타일 작업

2023-12-05 13:05 UTC, Jerome-Yoo approved these changes
제안과 질문 코멘트만 체크 부탁드립니다
일단 approve를 찍었어요!

2023-12-05 13:05 UTC, Jerome-Yoo commented on packages/ui/index.html
> +    <div id="root" style="height : 100%;"></div>
[제안]
이쪽은 전체 브라우저 지면을 쓰기 위함인지 궁금합니다. 만약 그렇다면 100%말고 100vh가 되어야 하는것은 아닌지 궁금해요.

2023-12-05 13:05 UTC, Jerome-Yoo commented on packages/ui/src/App.tsx
> +                      height="100%">
[질문]
저는 이런식으로 프로퍼티로 관리하는 경험이 괜찮은데 혹시 어떤지 궁금해요. @divinity6 
tailwind를 활용하게 되면 이런 부분도 className으로 관리해야할 것 같다는 생각이 들었습니다.

2023-12-05 13:05 UTC, Jerome-Yoo commented on packages/ui/src/components/view/loginView.tsx
뷰라는 이름이 약간 어색하기는 하지만, 요것은 제가 일단 적응해보겠습니다! 🙇

2023-12-10 10:06 UTC, divinity6 commented on packages/ui/index.html
> +    <div id="root" style="height : 100%;"></div>
100vh 로 수정했습니다!

2023-12-10 10:14 UTC, divinity6 commented on packages/ui/src/App.tsx
> +                      height="100%">
일단은 익숙한 스타일프로퍼티로 작성해두었는데, 추후 한꺼번에 리팩터링하도록 하겠습니다!

2023-12-13 00:57 UTC, Jerome-Yoo requested changes
고생하셨어요!
적극 라벨을 붙인 코멘트가 있어서 RC 상태로 전달드립니다. @divinity6

2023-12-13 00:57 UTC, Jerome-Yoo commented on apps/web/src/pages/index.tsx
> +    const { LoginView , onLoginClick } = useLogin();
[적극] 오 훅 기반으로 전환을 시도하셨군요!🙂
좋은 시도라고 판단합니다👍🏻👍🏻

다만 훅이 컴포넌트 함수 혹은 렌더부 자체를 리턴하는 경우는 흔치 않습니다.
그래서 리뷰에 적극 라벨을 달았어요.

훅의 컨셉이 렌더부와 로직을 분리하기 위함이고, 
보다 직관적으로는 주입되는 프로퍼티 자체를 없애는 용도로 사용하거나, 상위에서 주입하는 프로퍼티를 공통의 영역으로부터 "끌어다 쓰는" 컨셉으로 활용된다는 것을 파악해주시면 감사드리겠습니다.

지금의 경우에서는 로그인뷰 자체에서 훅을 실행하는 것으로 변경하는 것 혹은 로그인뷰 실행 시점(JSX) 에 프롭으로 핸들러를 넘기는 것에 의미가 있다고 보여져요.

예시가 되는 링크에 카운터 예제와 keypress 예제가 코드샌드박스로 있는데요, 그것을 참고해보시는 것은 어떨까요.
https://patterns-dev-kr.github.io/design-patterns/hooks-pattern/

2023-12-18 12:45 UTC, divinity6 commented on apps/web/src/pages/index.tsx
> +    const { LoginView , onLoginClick } = useLogin();
네넵 확인했습니다!

리액트 hook 을 적극사용한다면, hook 자체에서 공용 View 와 비즈니스로직등을 제공해주면 좋겠다고 생각했는데

주신 예제에서는 hook 에서 단지 상태 핸들링만 처리하는군요 

상태 프로퍼티들을 핸들링하는 영역으로 좀 더 범위를 좁게 좁혀 작업하도록하겠습니다!

2023-12-26 15:00 UTC, divinity6 commented
퍼블리싱 마무리되었습니다. 머지는 내일 리뷰 후 진행하도록 하겠습니다!

2023-12-27 13:48 UTC, Jerome-Yoo commented
@divinity6 12시까지 리뷰 하겠습니다!

2023-12-27 14:05 UTC, Jerome-Yoo approved these changes
@divinity6 적극 코멘트와 제안 코멘트를 남겼습니다. 원래라면 머지되지 않고 개선을 해야하는 상황이긴 하지만, 일단 상황이 상황인지라 머지를 선행 하고 리팩터링 PR을 오픈하는 것이 어떨까요?

2023-12-27 14:05 UTC, Jerome-Yoo commented on apps/web/src/pages/index.tsx
> +  }, []);
[제안]
혹시 해당 로직에서 기대하시는 바가 무엇인가요? 앞으로 fetch 로직이 들어가는 상황인지 궁금합니다.
만약 mounted만 관심사가 있는 상황이라면, 이 영역은 라이프사이클 기준으로 처리되는 지라 지워져도 괜찮을 것 같아요.

2023-12-27 14:05 UTC, Jerome-Yoo commented on packages/ui/src/assets/tailwind.css
> +}
오 폰트 잡아주셔서 감사합니다! 
[질문] 저희 노토산스도 쓰는 상황인가요?

2023-12-27 14:05 UTC, Jerome-Yoo commented on packages/ui/src/components/base/button/BaseButtonMain.tsx
> +                style={ { backgroundColor : `#FF6625` , cursor: 'pointer' } }
[제안] 백그라운드 컬러는 테마든 유틸이든 향후 디자인 토큰정보를 활용하는 형태가 되면 좋을 것 같아요.

2023-12-27 14:05 UTC, Jerome-Yoo commented on packages/ui/src/components/view/LoginView.tsx
> +          </div>
[제안] 이쪽은 Radix의 `Flex` 컴포넌트를 사용하면 좋을 것 같아요

2023-12-27 14:05 UTC, Jerome-Yoo commented on packages/ui/src/components/view/LoginView.tsx
> +          </div>
아래에도 동일한 영역이 있어서 같이 처리 부탁드립니다!

2023-12-27 14:05 UTC, Jerome-Yoo commented on packages/ui/src/components/view/signup/SignupView.tsx
> +  ] );
[질문] 이쪽은 향후 백엔드 영역을 받아서 처리되는 것이 맞죠? 지금은 목데이터와 동일한 상황이구요! 그렇다면 일단은 넘어갈 수 있을 것 같습니다.

2023-12-27 14:05 UTC, Jerome-Yoo commented on packages/ui/src/components/view/signup/SignupView.tsx
> +        { chipList && chipList.map( ( chip , chipIndex ) => (
[제안]
```suggestion
        { chipList?.map( ( chip , chipIndex ) => (
```
이렇게 해도 될 것 같습니다.

2023-12-27 14:05 UTC, Jerome-Yoo commented on packages/ui/src/components/view/signup/SignupView.tsx
> +SignupView.CategoryChip = ( { onClick , isActive , children } ) => {
[적극 제안]
SignupView 함수의 프로토타입에 직접 접근해서 확장하는 방식이 안전하지 못하다는 생각이 듭니다. 
실제로 SignupView에 선언된 함수나 프로퍼티를 직접 접근해서 사용하지 않고 함수 인자로서 내려받는 상황이라 이 부분은 함수 역할과 책임 차원에서 분리해서 선언하는 것이 맞다는 생각이 들어요. 위에 모달도 같은 패턴으로 되어있더라구요. 만약 합성컴포넌트의 형태를 작성하기를 바라셨다면, Object.assign을 활용해서 https://fe-developers.kakaoent.com/2022/220731-composition-component/#3-3-%EB%A9%94%EC%9D%B8--%EC%84%9C%EB%B8%8C-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EB%A5%BC-%EB%AC%B6%EC%96%B4%EC%84%9C-export 이런식으로 처리하는 것을 권장드려봅니다.

2023-12-27 14:05 UTC, Jerome-Yoo commented on packages/ui/src/components/view/signup/SignupView.tsx
> +  }
[적극 제안]
onClick이 undefined인 경우 해당 prop의 값을 직접 수정하는 것은 immutable하지 못한 접근방식이라 개선이 필요합니다.
onClick 실행시점에 if 문으로 조절하는 것도 방법이 된다고 생각합니다!

2023-12-27 14:20 UTC, merged